name: Bug
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a bug report. To address this bug as fast as possible, we need some information.
  - type: textarea
    id: bug_desc
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true
  - type: dropdown
    id: bug_os
    attritubes:
      label: On what operating system did you get this bug?
      options:
        - Windows 7
        - Windows 8
        - Windows 8.1
        - Windows 10
        - Windows 11
    validations:
      required: true
